gg_rct_UndergroundMap = nil
gg_rct_SurfaceMap = nil
gg_rct_TestSurface = nil
gg_rct_TestUnderground = nil
gg_rct_Surface2 = nil
gg_rct_Underground2 = nil
gg_trg_Untitled_Trigger_001 = nil
gg_unit_o002_0132 = nil
function InitGlobals()
end

function CreateAllItems()
    local itemID
    BlzCreateItemWithSkin(FourCC("IMF1"), -11991.6, -12351.6, FourCC("IMF1"))
    BlzCreateItemWithSkin(FourCC("IMF1"), -12028.1, -12287.1, FourCC("IMF1"))
    BlzCreateItemWithSkin(FourCC("IMF1"), -11931.7, -12485.8, FourCC("IMF1"))
    BlzCreateItemWithSkin(FourCC("IMF1"), -11968.2, -12421.3, FourCC("IMF1"))
    BlzCreateItemWithSkin(FourCC("IMF2"), -12205.2, -12404.6, FourCC("IMF2"))
    BlzCreateItemWithSkin(FourCC("IMF2"), -12160.3, -12463.5, FourCC("IMF2"))
    BlzCreateItemWithSkin(FourCC("IMF2"), -12100.4, -12597.7, FourCC("IMF2"))
    BlzCreateItemWithSkin(FourCC("IMF2"), -12145.3, -12538.8, FourCC("IMF2"))
    BlzCreateItemWithSkin(FourCC("IMF3"), -11870.9, -12409.9, FourCC("IMF3"))
    BlzCreateItemWithSkin(FourCC("IMF3"), -11930.8, -12275.7, FourCC("IMF3"))
    BlzCreateItemWithSkin(FourCC("IMF3"), -11894.4, -12340.2, FourCC("IMF3"))
    BlzCreateItemWithSkin(FourCC("IMF3"), -11834.5, -12474.4, FourCC("IMF3"))
    BlzCreateItemWithSkin(FourCC("IMM1"), -12298.4, -12374.8, FourCC("IMM1"))
    BlzCreateItemWithSkin(FourCC("IMM1"), -12334.9, -12310.3, FourCC("IMM1"))
    BlzCreateItemWithSkin(FourCC("IMM1"), -12238.5, -12509.0, FourCC("IMM1"))
    BlzCreateItemWithSkin(FourCC("IMM1"), -12275.0, -12444.5, FourCC("IMM1"))
    BlzCreateItemWithSkin(FourCC("IMM1"), -12059.3, -12430.1, FourCC("IMM1"))
    BlzCreateItemWithSkin(FourCC("IMM1"), -12022.8, -12494.6, FourCC("IMM1"))
    BlzCreateItemWithSkin(FourCC("IMM1"), -12119.2, -12295.9, FourCC("IMM1"))
    BlzCreateItemWithSkin(FourCC("IMM1"), -12082.7, -12360.5, FourCC("IMM1"))
    BlzCreateItemWithSkin(FourCC("IMM2"), -12200.1, -12159.4, FourCC("IMM2"))
    BlzCreateItemWithSkin(FourCC("IMM2"), -12174.6, -12208.2, FourCC("IMM2"))
    BlzCreateItemWithSkin(FourCC("IMM3"), -12172.2, -12030.5, FourCC("IMM3"))
    BlzCreateItemWithSkin(FourCC("IMM3"), -12157.7, -12069.4, FourCC("IMM3"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11149.5, -12557.8, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11179.3, -12578.5, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11118.6, -12628.7, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -10978.4, -12497.9, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11401.2, -12967.5, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11028.7, -13103.6, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11904.9, -12042.2, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11102.4, -12347.0, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11132.2, -12367.7, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11071.5, -12417.8, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11026.3, -12548.1, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11056.1, -12568.8, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -10995.4, -12618.9, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11009.3, -12427.0, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11039.1, -12447.8, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11371.4, -12946.8, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -10908.6, -12816.3, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11123.0, -12478.2, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11183.7, -12428.1, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11912.6, -11928.0, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS1"), -11154.0, -12407.4, FourCC("IMS1"))
    BlzCreateItemWithSkin(FourCC("IMS2"), -11332.2, -12640.5, FourCC("IMS2"))
    BlzCreateItemWithSkin(FourCC("IMS2"), -11465.3, -12677.0, FourCC("IMS2"))
    BlzCreateItemWithSkin(FourCC("IMS2"), -11375.7, -13046.6, FourCC("IMS2"))
    BlzCreateItemWithSkin(FourCC("IMS2"), -11352.6, -13101.9, FourCC("IMS2"))
    BlzCreateItemWithSkin(FourCC("IMS2"), -11485.7, -13138.4, FourCC("IMS2"))
    BlzCreateItemWithSkin(FourCC("IMS2"), -11440.5, -13082.6, FourCC("IMS2"))
    BlzCreateItemWithSkin(FourCC("IMS2"), -11420.1, -12621.1, FourCC("IMS2"))
    BlzCreateItemWithSkin(FourCC("IMS2"), -11355.3, -12585.2, FourCC("IMS2"))
    BlzCreateItemWithSkin(FourCC("IMS3"), -11121.9, -13065.0, FourCC("IMS3"))
    BlzCreateItemWithSkin(FourCC("IMS3"), -11199.7, -13041.0, FourCC("IMS3"))
    BlzCreateItemWithSkin(FourCC("IMS3"), -11235.9, -13146.0, FourCC("IMS3"))
    BlzCreateItemWithSkin(FourCC("IMS3"), -11180.7, -13104.7, FourCC("IMS3"))
    BlzCreateItemWithSkin(FourCC("IMW1"), -11805.1, -11953.8, FourCC("IMW1"))
    BlzCreateItemWithSkin(FourCC("IMW1"), -11348.3, -12502.4, FourCC("IMW1"))
    BlzCreateItemWithSkin(FourCC("IMW1"), -11484.8, -12967.5, FourCC("IMW1"))
    BlzCreateItemWithSkin(FourCC("IMW1"), -11492.7, -12886.8, FourCC("IMW1"))
    BlzCreateItemWithSkin(FourCC("IMW1"), -11848.4, -11986.4, FourCC("IMW1"))
    BlzCreateItemWithSkin(FourCC("IMW1"), -11356.2, -12421.7, FourCC("IMW1"))
    BlzCreateItemWithSkin(FourCC("IMW2"), -11484.7, -13040.0, FourCC("IMW2"))
    BlzCreateItemWithSkin(FourCC("IMW2"), -11375.4, -13182.0, FourCC("IMW2"))
    BlzCreateItemWithSkin(FourCC("IMW2"), -11308.7, -12946.8, FourCC("IMW2"))
    BlzCreateItemWithSkin(FourCC("IMW2"), -11387.1, -12886.8, FourCC("IMW2"))
    BlzCreateItemWithSkin(FourCC("IPC1"), -11533.1, -12407.2, FourCC("IPC1"))
    BlzCreateItemWithSkin(FourCC("IPC1"), -11719.1, -11993.5, FourCC("IPC1"))
    BlzCreateItemWithSkin(FourCC("IPC2"), -11542.0, -12288.0, FourCC("IPC2"))
    BlzCreateItemWithSkin(FourCC("IPC2"), -11723.5, -11911.7, FourCC("IPC2"))
    BlzCreateItemWithSkin(FourCC("IPC3"), -11533.2, -12189.6, FourCC("IPC3"))
    BlzCreateItemWithSkin(FourCC("IPC3"), -11666.5, -11915.9, FourCC("IPC3"))
    BlzCreateItemWithSkin(FourCC("IPC4"), -11538.1, -12059.4, FourCC("IPC4"))
    BlzCreateItemWithSkin(FourCC("IPC4"), -11662.0, -11996.5, FourCC("IPC4"))
    BlzCreateItemWithSkin(FourCC("IPF1"), -11785.9, -12425.6, FourCC("IPF1"))
    BlzCreateItemWithSkin(FourCC("IPF2"), -11817.6, -12335.7, FourCC("IPF2"))
    BlzCreateItemWithSkin(FourCC("IPF3"), -11827.1, -12242.4, FourCC("IPF3"))
    BlzCreateItemWithSkin(FourCC("IPF4"), -11831.4, -12133.9, FourCC("IPF4"))
    BlzCreateItemWithSkin(FourCC("IPM1"), -11699.0, -12409.1, FourCC("IPM1"))
    BlzCreateItemWithSkin(FourCC("IPM2"), -11699.3, -12310.7, FourCC("IPM2"))
    BlzCreateItemWithSkin(FourCC("IPM3"), -11697.8, -12210.6, FourCC("IPM3"))
    BlzCreateItemWithSkin(FourCC("IPM4"), -11695.7, -12109.0, FourCC("IPM4"))
    BlzCreateItemWithSkin(FourCC("IPT1"), -11681.0, -11560.3, FourCC("IPT1"))
    BlzCreateItemWithSkin(FourCC("IPT1"), -11610.7, -12409.1, FourCC("IPT1"))
    BlzCreateItemWithSkin(FourCC("IPT1"), -11667.4, -11396.4, FourCC("IPT1"))
    BlzCreateItemWithSkin(FourCC("IPT2"), -11592.0, -11551.6, FourCC("IPT2"))
    BlzCreateItemWithSkin(FourCC("IPT2"), -11578.4, -11387.7, FourCC("IPT2"))
    BlzCreateItemWithSkin(FourCC("IPT2"), -11614.4, -12319.8, FourCC("IPT2"))
    BlzCreateItemWithSkin(FourCC("IPT3"), -11481.4, -11545.7, FourCC("IPT3"))
    BlzCreateItemWithSkin(FourCC("IPT3"), -11614.1, -12209.0, FourCC("IPT3"))
    BlzCreateItemWithSkin(FourCC("IPT3"), -11467.8, -11381.8, FourCC("IPT3"))
    BlzCreateItemWithSkin(FourCC("IPT4"), -11361.8, -11541.5, FourCC("IPT4"))
    BlzCreateItemWithSkin(FourCC("IPT4"), -11611.5, -12089.3, FourCC("IPT4"))
    BlzCreateItemWithSkin(FourCC("IPT4"), -11348.2, -11377.7, FourCC("IPT4"))
    BlzCreateItemWithSkin(FourCC("IT00"), -11185.3, -12839.9, FourCC("IT00"))
    BlzCreateItemWithSkin(FourCC("IT01"), -11275.6, -13069.0, FourCC("IT01"))
    BlzCreateItemWithSkin(FourCC("IT01"), -11446.4, -12398.7, FourCC("IT01"))
    BlzCreateItemWithSkin(FourCC("IT01"), -11149.5, -12968.9, FourCC("IT01"))
    BlzCreateItemWithSkin(FourCC("IT03"), -11447.3, -12282.6, FourCC("IT03"))
    BlzCreateItemWithSkin(FourCC("IT04"), -11442.9, -12172.8, FourCC("IT04"))
    BlzCreateItemWithSkin(FourCC("IT05"), -11449.7, -12092.7, FourCC("IT05"))
end

function CreateBuildingsForPlayer0()
    local p = Player(0)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("o000"), -7648.0, -12768.0, 270.000, FourCC("o000"))
    u = BlzCreateUnitWithSkin(p, FourCC("ntnt"), -7648.0, -10912.0, 270.000, FourCC("ntnt"))
    u = BlzCreateUnitWithSkin(p, FourCC("nfh0"), -8064.0, -11008.0, 270.000, FourCC("nfh0"))
    u = BlzCreateUnitWithSkin(p, FourCC("nfh1"), -7840.0, -10976.0, 270.000, FourCC("nfh1"))
end

function CreateUnitsForPlayer0()
    local p = Player(0)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("o001"), -8091.8, -12739.2, 245.023, FourCC("o001"))
    gg_unit_o002_0132 = BlzCreateUnitWithSkin(p, FourCC("o002"), -12027.4, -12135.8, 303.686, FourCC("o002"))
end

function CreateBuildingsForPlayer11()
    local p = Player(11)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("uslh"), -10048.0, -11136.0, 270.000, FourCC("uslh"))
end

function CreateBuildingsForPlayer15()
    local p = Player(15)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("e000"), -12288.0, -11840.0, 270.000, FourCC("e000"))
    IssueImmediateOrder(u, "root")
    u = BlzCreateUnitWithSkin(p, FourCC("h000"), -10976.0, -11360.0, 270.000, FourCC("h000"))
    u = BlzCreateUnitWithSkin(p, FourCC("h003"), -10784.0, -11488.0, 270.000, FourCC("h003"))
    u = BlzCreateUnitWithSkin(p, FourCC("h004"), -10976.0, -11552.0, 270.000, FourCC("h004"))
    u = BlzCreateUnitWithSkin(p, FourCC("o004"), -10880.0, -11968.0, 270.000, FourCC("o004"))
end

function CreateUnitsForPlayer18()
    local p = Player(18)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("Hblm"), -5856.5, -12656.5, 3.210, FourCC("Hblm"))
    UnitAddItemToSlotById(u, FourCC("IM01"), 0)
    UnitAddItemToSlotById(u, FourCC("IM01"), 1)
    UnitAddItemToSlotById(u, FourCC("IM01"), 2)
    UnitAddItemToSlotById(u, FourCC("IM00"), 3)
    UnitAddItemToSlotById(u, FourCC("IM00"), 4)
    UnitAddItemToSlotById(u, FourCC("IM00"), 5)
end

function CreateBuildingsForPlayer20()
    local p = Player(20)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("o003"), -11296.0, -11872.0, 270.000, FourCC("o003"))
end

function CreateUnitsForPlayer21()
    local p = Player(21)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("Hblm"), -5584.1, -10828.1, 3.210, FourCC("Hblm"))
    UnitAddItemToSlotById(u, FourCC("IM01"), 0)
    UnitAddItemToSlotById(u, FourCC("IM01"), 1)
    UnitAddItemToSlotById(u, FourCC("IM01"), 2)
    UnitAddItemToSlotById(u, FourCC("IM00"), 3)
    UnitAddItemToSlotById(u, FourCC("IM00"), 4)
    UnitAddItemToSlotById(u, FourCC("IM00"), 5)
end

function CreateNeutralPassiveBuildings()
    local p = Player(PLAYER_NEUTRAL_PASSIVE)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("ngol"), -7936.0, -12096.0, 270.000, FourCC("ngol"))
    SetResourceAmount(u, 12500)
end

function CreatePlayerBuildings()
    CreateBuildingsForPlayer0()
    CreateBuildingsForPlayer11()
    CreateBuildingsForPlayer15()
    CreateBuildingsForPlayer20()
end

function CreatePlayerUnits()
    CreateUnitsForPlayer0()
    CreateUnitsForPlayer18()
    CreateUnitsForPlayer21()
end

function CreateAllUnits()
    CreateNeutralPassiveBuildings()
    CreatePlayerBuildings()
    CreatePlayerUnits()
end

function CreateRegions()
    local we
    gg_rct_UndergroundMap = Rect(-23552.0, -6784.0, -7552.0, 9216.0)
    gg_rct_SurfaceMap = Rect(-6784.0, -6784.0, 9216.0, 9216.0)
    gg_rct_TestSurface = Rect(-4448.0, -2784.0, 1696.0, 3360.0)
    gg_rct_TestUnderground = Rect(-18656.0, -2944.0, -12512.0, 3200.0)
    gg_rct_Surface2 = Rect(-5920.0, -4224.0, 3296.0, 4992.0)
    gg_rct_Underground2 = Rect(-20128.0, -4544.0, -10912.0, 4672.0)
end

--
function Trig_Untitled_Trigger_001_Actions()
    AddSpecialEffectTargetUnitBJ("Slot1", gg_unit_o002_0132, "Abilities\\Spells\\Other\\TalkToMe\\TalkToMe.mdl")
end

function InitTrig_Untitled_Trigger_001()
    gg_trg_Untitled_Trigger_001 = CreateTrigger()
    TriggerRegisterPlayerChatEvent(gg_trg_Untitled_Trigger_001, Player(0), "-do", true)
    TriggerAddAction(gg_trg_Untitled_Trigger_001, Trig_Untitled_Trigger_001_Actions)
end

function InitCustomTriggers()
    InitTrig_Untitled_Trigger_001()
end

function InitCustomPlayerSlots()
    SetPlayerStartLocation(Player(0), 0)
    ForcePlayerStartLocation(Player(0), 0)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerRacePreference(Player(0), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(0), false)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(1), 1)
    ForcePlayerStartLocation(Player(1), 1)
    SetPlayerColor(Player(1), ConvertPlayerColor(1))
    SetPlayerRacePreference(Player(1), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(1), false)
    SetPlayerController(Player(1), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(2), 2)
    ForcePlayerStartLocation(Player(2), 2)
    SetPlayerColor(Player(2), ConvertPlayerColor(2))
    SetPlayerRacePreference(Player(2), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(2), false)
    SetPlayerController(Player(2), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(3), 3)
    ForcePlayerStartLocation(Player(3), 3)
    SetPlayerColor(Player(3), ConvertPlayerColor(3))
    SetPlayerRacePreference(Player(3), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(3), false)
    SetPlayerController(Player(3), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(4), 4)
    ForcePlayerStartLocation(Player(4), 4)
    SetPlayerColor(Player(4), ConvertPlayerColor(4))
    SetPlayerRacePreference(Player(4), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(4), false)
    SetPlayerController(Player(4), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(5), 5)
    ForcePlayerStartLocation(Player(5), 5)
    SetPlayerColor(Player(5), ConvertPlayerColor(5))
    SetPlayerRacePreference(Player(5), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(5), false)
    SetPlayerController(Player(5), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(6), 6)
    ForcePlayerStartLocation(Player(6), 6)
    SetPlayerColor(Player(6), ConvertPlayerColor(6))
    SetPlayerRacePreference(Player(6), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(6), false)
    SetPlayerController(Player(6), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(7), 7)
    ForcePlayerStartLocation(Player(7), 7)
    SetPlayerColor(Player(7), ConvertPlayerColor(7))
    SetPlayerRacePreference(Player(7), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(7), false)
    SetPlayerController(Player(7), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(8), 8)
    ForcePlayerStartLocation(Player(8), 8)
    SetPlayerColor(Player(8), ConvertPlayerColor(8))
    SetPlayerRacePreference(Player(8), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(8), false)
    SetPlayerController(Player(8), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(9), 9)
    ForcePlayerStartLocation(Player(9), 9)
    SetPlayerColor(Player(9), ConvertPlayerColor(9))
    SetPlayerRacePreference(Player(9), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(9), false)
    SetPlayerController(Player(9), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(11), 10)
    ForcePlayerStartLocation(Player(11), 10)
    SetPlayerColor(Player(11), ConvertPlayerColor(11))
    SetPlayerRacePreference(Player(11), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(11), false)
    SetPlayerController(Player(11), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(15), 11)
    ForcePlayerStartLocation(Player(15), 11)
    SetPlayerColor(Player(15), ConvertPlayerColor(15))
    SetPlayerRacePreference(Player(15), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(15), false)
    SetPlayerController(Player(15), MAP_CONTROL_NEUTRAL)
    SetPlayerStartLocation(Player(20), 12)
    ForcePlayerStartLocation(Player(20), 12)
    SetPlayerColor(Player(20), ConvertPlayerColor(20))
    SetPlayerRacePreference(Player(20), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(20), false)
    SetPlayerController(Player(20), MAP_CONTROL_NEUTRAL)
end

function InitCustomTeams()
    SetPlayerTeam(Player(0), 0)
    SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(1), 0)
    SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(2), 0)
    SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(3), 0)
    SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(4), 0)
    SetPlayerState(Player(4), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(5), 0)
    SetPlayerState(Player(5), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(6), 0)
    SetPlayerState(Player(6), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(7), 0)
    SetPlayerState(Player(7), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(8), 0)
    SetPlayerState(Player(8), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(9), 0)
    SetPlayerState(Player(9), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(15), 0)
    SetPlayerState(Player(15), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(20), 0)
    SetPlayerState(Player(20), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(6), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(7), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(8), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(15), true)
    SetPlayerAllianceStateAllyBJ(Player(9), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(15), Player(20), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(6), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(7), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(8), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(9), true)
    SetPlayerAllianceStateAllyBJ(Player(20), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(6), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(7), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(8), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(15), true)
    SetPlayerAllianceStateVisionBJ(Player(9), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(15), Player(20), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(6), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(7), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(8), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(9), true)
    SetPlayerAllianceStateVisionBJ(Player(20), Player(15), true)
    SetPlayerTeam(Player(11), 1)
    SetPlayerState(Player(11), PLAYER_STATE_ALLIED_VICTORY, 1)
end

function InitAllyPriorities()
    SetStartLocPrioCount(0, 9)
    SetStartLocPrio(0, 0, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 2, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 3, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(0, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(1, 9)
    SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 2, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 3, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(2, 9)
    SetStartLocPrio(2, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 2, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 3, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(2, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(3, 9)
    SetStartLocPrio(3, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 3, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(3, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(4, 9)
    SetStartLocPrio(4, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 4, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(5, 9)
    SetStartLocPrio(5, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 5, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(5, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(6, 9)
    SetStartLocPrio(6, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 5, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 6, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(6, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(7, 9)
    SetStartLocPrio(7, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 5, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 6, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 7, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(7, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(8, 9)
    SetStartLocPrio(8, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 5, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 6, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 7, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(8, 8, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(9, 9)
    SetStartLocPrio(9, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 1, 1, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 2, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 3, 3, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 4, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 5, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 6, 6, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 7, 7, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(9, 8, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(10, 8)
    SetStartLocPrio(10, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 1, 2, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(10, 2, 4, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(10, 3, 5, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(10, 4, 6, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(10, 5, 8, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(10, 6, 9, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(10, 4)
    SetEnemyStartLocPrio(10, 0, 5, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(10, 1, 6, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(10, 2, 8, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(10, 3, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(11, 9)
    SetStartLocPrio(11, 0, 4, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(11, 1, 5, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(11, 2, 6, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(11, 3, 7, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(11, 4, 8, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(11, 5, 9, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(11, 6, 10, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(11, 7, 12, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(11, 5)
    SetEnemyStartLocPrio(11, 0, 4, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(11, 1, 5, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(11, 2, 6, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(11, 3, 8, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(11, 4, 9, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(12, 8)
    SetStartLocPrio(12, 0, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(12, 1, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(12, 2, 6, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(12, 3, 7, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(12, 4, 8, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(12, 5, 9, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(12, 6, 10, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrioCount(12, 4)
    SetEnemyStartLocPrio(12, 0, 5, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(12, 1, 7, MAP_LOC_PRIO_HIGH)
    SetEnemyStartLocPrio(12, 2, 8, MAP_LOC_PRIO_LOW)
    SetEnemyStartLocPrio(12, 3, 9, MAP_LOC_PRIO_LOW)
end

function main()
    SetCameraBounds(-22784.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -23040.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 8448.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 8192.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -22784.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 8192.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 8448.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -23040.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    SetTerrainFogEx(0, 25000.0, 25000.0, 0.500, 0.000, 0.000, 0.000)
    NewSoundEnvironment("Default")
    SetAmbientDaySound("LordaeronSummerDay")
    SetAmbientNightSound("LordaeronSummerNight")
    SetMapMusic("Music", true, 0)
    CreateRegions()
    CreateAllItems()
    CreateAllUnits()
    InitBlizzard()
    InitGlobals()
    InitCustomTriggers()
end

function config()
    SetMapName("TRIGSTR_001")
    SetMapDescription("TRIGSTR_003")
    SetPlayers(13)
    SetTeams(13)
    SetGamePlacement(MAP_PLACEMENT_TEAMS_TOGETHER)
    DefineStartLocation(0, -1408.0, 320.0)
    DefineStartLocation(1, -1408.0, 320.0)
    DefineStartLocation(2, -1408.0, 320.0)
    DefineStartLocation(3, -1408.0, 320.0)
    DefineStartLocation(4, -1408.0, 320.0)
    DefineStartLocation(5, -1408.0, 320.0)
    DefineStartLocation(6, -1408.0, 320.0)
    DefineStartLocation(7, -1408.0, 320.0)
    DefineStartLocation(8, -1408.0, 320.0)
    DefineStartLocation(9, -1408.0, 320.0)
    DefineStartLocation(10, -1408.0, 320.0)
    DefineStartLocation(11, -1408.0, 320.0)
    DefineStartLocation(12, -10624.0, -11712.0)
    InitCustomPlayerSlots()
    InitCustomTeams()
    InitAllyPriorities()
end

